version: '3'
services:
  horilla_server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@horilla_postgres:5432/${POSTGRES_DB:-horilla}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-change_this_in_production}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      - DJANGO_ALLOWED_HOSTS=${DOMAIN:-*}
    command: ./entrypoint.sh
    networks:
      - proxy_manager
    restart: always
    depends_on:
      horilla_postgres:
        condition: service_healthy

  horilla_postgres:
    image: postgres:16-bullseye
    container_name: horilla_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-horilla}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - /media/bigstore/horilla_postgres_data:/var/lib/postgresql/data
    networks:
      - proxy_manager
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  proxy_manager:
    external: true